from hype.element import (H1, H2, H3, H4, H5, H6, A, Abbr, Address, Area,
                          Article, Aside, Audio, B, Base, Bdi, Bdo, Blockquote,
                          Body, Br, Button, Canvas, Caption, Cite, Code, Col,
                          Colgroup, Data, Datalist, Dd, Del, Details, Dfn,
                          Dialog, Div, Dl, Doc, Dt, Element, Em, Embed,
                          Fieldset, Figcaption, Figure, Footer, Form, Head,
                          Header, Hgroup, Hr, Html, I, Iframe, Img, Indent,
                          Input, Ins, Kbd, Label, Legend, Li, Link, Main, Map,
                          Mark, Math, Menu, Menuitem, Meta, Meter, Nav,
                          Noscript, Object, Ol, Optgroup, Option, Output, P,
                          Param, Picture, Pre, Progress, Q, Rb, Rp, Rt, Rtc,
                          Ruby, S, Samp, Script, Section, Select,
                          SelfClosingElement, Slot, Small, Source, Span,
                          Strong, Style, Sub, Summary, Sup, Svg, Table, Tbody,
                          Td, Template, Textarea, Tfoot, Th, Thead, Time,
                          Title, Tr, Track, U, Ul, Var, Video, Wbr)
